Feature/setup filter form
toggle-corp/mmp-dashboard pull request #1
Opened 2021-05-23 12:30 UTC by AdityaKhatri

2021-05-24 07:56 UTC, tnagorra commented on src/Root/App/index.tsx
> +    };
Please memoize requestContextValue.

2021-05-24 07:57 UTC, tnagorra commented on src/Root/App/index.tsx
> +        transformOptions: (_: string, options) => processOptions(options),
Please specify type for options argument

2021-05-24 07:58 UTC, tnagorra commented on src/Root/App/styles.css
> +    --tui-color-accent: #6558f5;
Please re-use previously defined variable

```suggestion
    --tui-color-primary: var(--color-primary);
    --tui-color-accent: var(--color-accent);
```

2021-05-24 08:38 UTC, tnagorra requested changes

2021-05-24 08:38 UTC, tnagorra commented on src/Root/App/styles.css
> +    --color-background-alternate: #dfe6ed;
Please add comment how this is different from `color-background`

2021-05-24 08:38 UTC, tnagorra commented on src/components/TagInput/index.tsx
> +}
Isn't this already a separate component?

2021-05-24 08:38 UTC, tnagorra commented on src/components/TagInput/index.tsx
> +const keySelector = (d: string) => d;
Please move keySelector before Props definition for TagInput

2021-05-24 08:38 UTC, tnagorra commented on src/components/TagInput/index.tsx
> +interface Props<N> {
```suggestion
interface Props<N extends string> {
```

2021-05-24 08:38 UTC, tnagorra commented on src/components/TagInput/index.tsx
> +        value = [],
We should not create new object/array on render

2021-05-24 08:38 UTC, tnagorra commented on src/components/TagInput/index.tsx
> +    }, []);
```suggestion
    const handleNewTagValueAdd = setNewTagValue;
```

2021-05-24 08:38 UTC, tnagorra commented on src/components/TagInput/index.tsx
> +                                name="remove"
Did you mean name="add"?

2021-05-24 08:38 UTC, tnagorra commented on src/hooks/useBooleanState.ts
> +    return [value, setTrue, setFalse, setValue, toggleFn];
```suggestion
    return [value, setTrue, setFalse, setValue, toggleFn] as const;
```

2021-05-24 08:38 UTC, tnagorra commented on src/views/Home/Article/index.tsx
> +import styles from './styles.css';
```suggestion
import TagInput from '#components/TagInput';

import { Article as ArticleProps } from '..';
import styles from './styles.css';
```

2021-05-24 08:38 UTC, tnagorra commented on src/views/Home/Article/index.tsx
> +import { Article as ArticleProps } from '..';
```suggestion
import type { Article as ArticleProps } from '..';
```

2021-05-24 08:38 UTC, tnagorra commented on src/views/Home/Article/index.tsx
> +                    )}
Please pass icon as children when there is no text.

2021-05-24 08:38 UTC, tnagorra commented on src/views/Home/Filters/index.tsx
> +    includeAllKeywords: ['1st tag', '2nd tag'],
Why did we add these as default values? Are they temporary?

2021-05-24 08:38 UTC, tnagorra commented on src/views/Home/Filters/index.tsx
> +function Home(props: Props) {
```suggestion
function HomeFilters(props: Props) {
```

2021-05-24 08:38 UTC, tnagorra commented on src/views/Home/Filters/index.tsx
> +            <h1 className={styles.heading}>Explore MMP</h1>
```suggestion
            <h1 className={styles.heading}>
                Explore MMP
            </h1>
```

2021-05-24 08:38 UTC, tnagorra commented on src/views/Home/Filters/index.tsx
> +                    onClick={handleFiltersReset}
Can we not disable the reset button when there is no change on filters?

2021-05-24 08:38 UTC, tnagorra commented on src/views/Home/index.tsx
> +    const [searchBody, setSearchBody] = useState(undefined);
Let's move this to request context.
The type for searchBody is not defined!

2021-05-24 08:38 UTC, tnagorra commented on src/views/Home/index.tsx
> +    const articleRendererParams = useCallback((_, data) => ({
Please define type for data

2021-05-24 08:38 UTC, tnagorra commented on src/views/Home/index.tsx
> +    }, []);
```suggestion
    const handleSearch = setSearchBody;
```

2021-05-24 08:38 UTC, tnagorra commented on src/views/Home/index.tsx
> +                    {articlesResponse?.results ? (
Please also check if length is greater than zero!

2021-05-24 08:38 UTC, tnagorra commented on src/views/Home/index.tsx
> +                        </h2>
This is semantically not correct!

2021-06-02 06:48 UTC, AdityaKhatri commented on src/components/TagInput/index.tsx
> +}
No, It has been included as TagView

2021-06-03 04:53 UTC, tnagorra requested changes

2021-06-03 04:53 UTC, tnagorra commented on package.json
> +        "build": "yarn run build:raw",
Why not just rename `build:raw` to `build`

2021-06-03 04:53 UTC, tnagorra commented on package.json
> +        "lint": "eslint ./src",
Why remove typecheck?

2021-06-03 05:02 UTC, tnagorra requested changes

2021-06-03 05:02 UTC, tnagorra commented on src/views/Login/index.tsx
> +        console.warn('i am here', completeValue, setUser);
```suggestion
```

2021-06-03 05:19 UTC, AdityaKhatri commented on src/Root/App/Multiplexer/index.tsx
> +     */
This is done to skip auth.
As soon as we setup auth, we'll have this back.

2021-06-03 05:23 UTC, AdityaKhatri commented on src/views/Home/Filters/index.tsx
> +                    onClick={handleFiltersReset}
We can, but chose not to :D

2021-06-04 04:54 UTC, tnagorra commented on src/views/Home/Filters/index.tsx
> +                    onClick={handleFiltersReset}
Please choose to do it.

2021-06-04 05:59 UTC, tnagorra requested changes

2021-06-04 05:59 UTC, tnagorra commented on src/views/Home/Filters/index.tsx
> +    const disableReset = value === defaultFormValues;
```suggestion
    const resetDisabled = value === defaultFormValues;
```

2021-06-04 06:29 UTC, tnagorra approved these changes

2021-06-04 06:31 UTC, merged