Add Relevancy/Non-relevancy filter
toggle-corp/mmp-dashboard pull request #12
Opened 2021-09-08 11:14 UTC by samshara

depends on https://github.com/toggle-corp/iom-project/pull/17
* Add CheckListInput component
* Add is_relevant filter to search API

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [ ] permission checks

2021-09-08 11:20 UTC, AdityaKhatri commented on src/views/Home/Filters/CheckListInput/CheckboxInput/index.tsx
> +function CheckboxInput<N extends OptionKey>(props: Props<N>) {
Can't we use Checkbox from toggle-ui?

2021-09-08 11:21 UTC, AdityaKhatri commented on src/views/Home/Filters/CheckListInput/index.tsx
> +} from '@togglecorp/toggle-ui';
Lets create this in toggle-ui and use it here?
That might make more sense.

2021-09-08 11:21 UTC, AdityaKhatri requested changes
Lets use Checkbox from toggle-ui. I recommend creating CheckboxList in toggle-ui as it is necessary for other projects as well.

2021-09-10 08:03 UTC, ranjan-stha requested changes

2021-09-10 08:03 UTC, ranjan-stha commented on src/views/Home/index.tsx
> +            is_relvant: searchBody?.isRelevant ?? [],
@samshara typo in the key name.

2021-09-10 08:03 UTC, samshara commented on src/views/Home/index.tsx
> +            is_relvant: searchBody?.isRelevant ?? [],
@ranjan-stha nice catch :+1:  :+1:

2021-09-10 11:45 UTC, merged