Create Popup for expanded article view
toggle-corp/mmp-dashboard pull request #3
Opened 2021-06-07 10:52 UTC by subinasr

2021-06-07 11:23 UTC, AdityaKhatri requested changes
Fix review requests.

2021-06-07 11:23 UTC, AdityaKhatri commented on src/views/Home/Article/ArticleDetail/index.tsx
> +        url: `/api/articles/${articleId}`,
```suggestion
        url: `/api/articles/${articleId}/`,
```
Always end your URLs with a `/`. Not having `/` at the end with redirect it to API with `/` and if servers are not configured properly, requests will be different.
Bottom line, adding a `/` at the end will reduce complications in most of the cases.

2021-06-07 11:23 UTC, AdityaKhatri commented on src/views/Home/Article/ArticleDetail/index.tsx
> +    const articleDetailData = response?.results && response.results[0];
@ranjan-stha , for individual items, we can directly send the item as its not really a list.
@subinasr , for now add a fix here, and after @ranjan-stha has implemented this in the server, lets fix it here.

2021-06-07 11:23 UTC, AdityaKhatri commented on src/views/Home/Article/ArticleDetail/index.tsx
> +        ? [articleDetailData?.language]
```suggestion
        ? [articleDetailData.language]
```

2021-06-07 11:58 UTC, AdityaKhatri requested changes

2021-06-07 11:58 UTC, AdityaKhatri commented on src/views/Home/Filters/index.tsx
> +    } = useForm(defaultValue, schema);
This throws an error, and is probably a mistake.

2021-06-07 11:58 UTC, AdityaKhatri commented on src/views/Home/Article/ArticleDetail/index.tsx
> +    }, []);
Lets not redefine these functions.
Could you send the handlers in ArticleDetail component from Article and trigger the function which exists in Article component.

2021-06-07 12:14 UTC, subinasr commented on src/views/Home/Article/ArticleDetail/index.tsx
> +        ? [articleDetailData?.language]
It throws an error 'object is possibly undefined'. 
I know we did the check in the upper line, but it still throws a type error.

2021-06-07 12:26 UTC, AdityaKhatri commented on src/views/Home/Article/ArticleDetail/index.tsx
> +    handleMarkAsIrrelevant: () => void;
```suggestion
    onMarkAsRelevantClick: () => void;
    onMarkAsIrrelevantClick: () => void;
```

2021-06-07 12:27 UTC, AdityaKhatri commented on src/views/Home/Article/ArticleDetail/index.tsx
> +    });
handle pending state, and show PendingMessage animation when request is pending

2021-06-07 12:28 UTC, AdityaKhatri commented on src/views/Home/Article/ArticleDetail/styles.css
> +    max-width: 70vw;
Have a fixed width and height for modal so that it doesn't resize when pending animation is shown.

2021-06-07 12:29 UTC, AdityaKhatri commented on src/views/Home/Article/ArticleDetail/styles.css
> +        }
Add color and padding the date similar to how it is in the Article component

2021-06-07 12:29 UTC, AdityaKhatri commented on src/views/Home/Article/ArticleDetail/index.tsx
> +        ? [articleDetailData?.language]
ok leave it as it then

2021-06-07 12:55 UTC, ranjan-stha commented on src/views/Home/Article/ArticleDetail/index.tsx
> +    });
@subinasr now the response of /api/articles/article_id returns an object instead of the list. The response would look like.
{
    "total": 1,
    "result": {
            .........
    }

If the article_id is somehow mismatched (for whatever reason), it would return

{
   "total": 0,
   "result": null
}

Pls kindly fix this in the frontend.

2021-06-07 13:50 UTC, AdityaKhatri commented on src/views/Home/Article/ArticleDetail/index.tsx
> +    });
@ranjan-stha , we wouldn't even need the total or result variables.
Let's send the result directly.

2021-06-07 15:28 UTC, ranjan-stha commented on src/views/Home/Article/ArticleDetail/index.tsx
> +    });
@AdityaKhatri @subinasr now it returns the payload object directly. If the resource is not found for some reason, it returns httpcode 404

2021-06-09 13:06 UTC, AdityaKhatri requested changes

2021-06-09 13:06 UTC, AdityaKhatri commented on src/views/Home/Article/ArticleDetail/index.tsx
> +    const [tabsValue, setTabsValue] = useState('extracted-text');
Define possible tabs as type and assign it here.
```suggestion
    type TabVariant = 'extracted-text' | 'smth';
    const [tabsValue, setTabsValue] = useState<TabVariant>('extracted-text');
```

2021-06-09 13:06 UTC, AdityaKhatri commented on src/views/Home/Article/ArticleDetail/index.tsx
> +    const handleTabChange = useCallback((name) => {
```suggestion
    const handleTabChange = useCallback((name: TabVaraint) => {
```

2021-06-09 13:06 UTC, AdityaKhatri commented on src/views/Home/Article/ArticleDetail/index.tsx
> +                                    Text from Source
```suggestion
                                    Original
```

2021-06-10 08:23 UTC, merged