Save filter values in dashboard
toggle-corp/mmp-dashboard pull request #5
Opened 2021-06-10 13:16 UTC by subinasr

- Addresses xxxxxx
- Depends on xxxxxx

## Changes

* Add Tab Component for 'explore-mmp' and 'daily-digest' view
* Save filter values for daily digest
* Style fixes for Tab component in the filter

## This PR doesn't introduce any:

- [ x ] temporary files, auto-generated files or secret keys
- [ x ] build works
- [ x ] eslint issues
- [ x ] typescript issues
- [ x ] `console.log` meant for debugging
- [ x ] typos
- [ x ] unwanted comments

## This PR contains valid:

- [ ] permission checks

Note: You may find two console.warn in the Article/index.tsx, I've attached a FIXME to it. It is to be removed after backend updates.

2021-06-13 14:24 UTC, AdityaKhatri commented
@subinasr , could you please fill out the PR checklist?

2021-06-13 14:28 UTC, AdityaKhatri requested changes
@subinasr , as soon as the page opens, we should fetch the articles with stored filters. That will make user experience better.

2021-06-13 14:28 UTC, AdityaKhatri commented on src/views/Home/Filters/index.tsx
> +                    disabled={isDefined(disableSearchOnPristine) && pristine}
Instead of this, we should fetch the data with prefilled form in the daily digest as soon as the page loads.

2021-06-15 03:49 UTC, tnagorra requested changes

2021-06-15 03:49 UTC, tnagorra commented on src/views/Home/index.tsx
> +    }, []);
We do not need to implement the function.

2021-06-17 07:03 UTC, merged