Feature/article relevancy
toggle-corp/mmp-dashboard pull request #9
Opened 2021-07-14 05:42 UTC by samshara

Set/Unset article relevancy in client

2021-07-14 05:51 UTC, AdityaKhatri approved these changes

2021-07-15 12:25 UTC, ranjan-stha requested changes

2021-07-15 12:25 UTC, ranjan-stha commented on src/views/Home/Article/index.tsx
> +        setRelevancy(true);
instead of true, pls send integer 1 because the is_relevant field in the backend is a choice field, not a boolean field.

2021-07-15 12:25 UTC, ranjan-stha commented on src/views/Home/Article/index.tsx
> +        setRelevancy(false);
instead of false, send 0 because the is_relevant field in the backend is a choice field, not a boolean field.

2021-07-21 06:13 UTC, merged